
# -----------------------------
# Server
# -----------------------------
spring.application.name=FraudRuleEngine
server.port=8080

# -----------------------------
# Datasource (local defaults, override via env)
# -----------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fraud}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fraud}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fraud}

spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------
# JPA / Hibernate
# -----------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# -----------------------------
# Flyway
# -----------------------------
spring.flyway.enabled=true

# -----------------------------
# Actuator
# -----------------------------
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# -----------------------------
# Logging
# -----------------------------
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSX} %5p [tx=%X{transactionId}] [%t] %logger{36} : %msg%n
logging.level.com.example.FraudRuleEngine=INFO



# -----------------------------
# Swagger UI
# -----------------------------
# springdoc.api-docs.path=/api-docs
# springdoc.swagger-ui.path=/swagger-ui.html
# springdoc.swagger-ui.operationsSorter=method
# springdoc.swagger-ui.tagsSorter=alpha



